# Generated by Django 5.2.6 on 2025-10-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tim1', models.CharField(max_length=50)),
                ('tim2', models.CharField(max_length=50)),
                ('skor_tim1', models.IntegerField()),
                ('skor_tim2', models.IntegerField()),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
