# Generated by Django 5.2.7 on 2025-10-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='sport',
            field=models.CharField(choices=[('NBA', 'NBA'), ('EPL', 'English Premier League'), ('NFL', 'NFL'), ('MLB', 'MLB'), ('NHL', 'NHL')], default='Unknown', max_length=10),
            preserve_default=False,
        ),
    ]
