# Generated by Django 5.2.7 on 2025-10-23 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_scoreboard_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('recent', 'Recent')], default='upcoming', max_length=10),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='tanggal',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
