# Generated by Django 5.2.7 on 2025-10-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_scoreboard_status_alter_scoreboard_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='logo_tim1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='logo_tim2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
