# Generated by Django 5.2.7 on 2025-10-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitur_pencarian', '0001_initial'),
        ('portal_berita', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpreference',
            name='default_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_preferences_brand', to='shop.brand'),
        ),
        migrations.AlterField(
            model_name='searchpreference',
            name='default_news_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_preferences_news', to='portal_berita.kategoriberita'),
        ),
        migrations.AlterField(
            model_name='searchpreference',
            name='default_product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_preferences_product', to='shop.category'),
        ),
    ]
