# Generated by Django 5.2.7 on 2025-10-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitur_pencarian", "0002_alter_searchpreference_default_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchpreference",
            name="role_visibility",
            field=models.CharField(
                choices=[
                    ("all", "Semua Pengguna"),
                    ("private", "Pribadi"),
                    ("staff", "Staf Saja"),
                ],
                default="all",
                help_text="Atur siapa yang dapat menggunakan preset ini.",
                max_length=20,
            ),
        ),
    ]
