# Generated by Django 5.2.7 on 2025-10-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitur_pencarian', '0003_alter_searchpreference_role_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpreference',
            name='role_visibility',
            field=models.CharField(choices=[('all', 'Semua Pengguna'), ('staff', 'Staf Saja'), ('private', 'Pribadi')], default='all', max_length=20),
        ),
    ]
