# Generated by Django 5.2.5 on 2025-10-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitur_pencarian', '0002_alter_searchpreference_default_brand_and_more'),
        ('fitur_pencarian', '0004_alter_searchpreference_role_visibility'),
    ]

    operations = [
    ]
