# Generated by Django 5.2.5 on 2025-10-08 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBerita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori Berita',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='KategoriProduk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori Produk',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255, unique=True)),
                ('ringkasan', models.TextField(blank=True, max_length=500)),
                ('konten', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('sumber', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True)),
                ('penulis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita', to='portal_berita.kategoriberita')),
            ],
            options={
                'ordering': ['-tanggal_dibuat'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('tanggal_ditambahkan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk', to='portal_berita.kategoriproduk')),
            ],
            options={
                'ordering': ['-tanggal_ditambahkan'],
            },
        ),
    ]
