# Generated by Django 5.2.5 on 2025-10-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_berita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='ringkasan',
        ),
        migrations.DeleteModel(
            name='KategoriProduk',
        ),
        migrations.DeleteModel(
            name='Produk',
        ),
    ]
