# Generated by Django 5.2.7 on 2025-10-24 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_berita', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='tanggal_dibuat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
