# Generated by Django 5.2.5 on 2025-10-18 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_berita', '0002_remove_produk_kategori_remove_berita_ringkasan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita', to='portal_berita.kategoriberita'),
        ),
    ]
