# Generated by Django 5.2.7 on 2025-10-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_berita', '0002_comment'),
    ]

    operations = []
