# Generated by Django 5.2.6 on 2025-10-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_berita', '0002_comment'),
        ('portal_berita', '0003_comment'),
    ]

    operations = [
    ]
