# Generated by Django 5.2.5 on 2025-10-24 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_berita', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='tanggal_dibuat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
