# Generated by ChatGPT to merge divergent portal_berita migration branches

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_berita', '0002_remove_produk_kategori_remove_berita_ringkasan_and_more'),
        ('portal_berita', '0003_alter_berita_kategori'),
    ]

    operations = []
