# Generated by Django 5.2.5 on 2025-10-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_berita', '0003_alter_berita_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
