# Generated by Django 5.2.7 on 2025-10-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal_berita", "0004_alter_berita_tanggal_dibuat"),
        ("portal_berita", "0004_merge_0002_comment_0003_comment"),
    ]

    operations = []
