# Generated by Django 5.2.6 on 2025-10-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_berita', '0002_alter_berita_tanggal_dibuat_comment'),
        ('portal_berita', '0005_merge_20251024_1442'),
    ]

    operations = [
    ]
