# Generated by Django 5.2.6 on 2025-10-23 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitur_belanja', '0001_initial'),
        ('shop', '0002_seed_products_fixed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'session_key'], name='fitur_belan_user_id_ab7b2f_idx'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='name_snapshot',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price_snapshot',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_id',
        ),
    ]

    operations = [
    migrations.RemoveField(
        model_name='order',
        name='user',
    ),
    migrations.RemoveField(
        model_name='orderitem',
        name='order',
    ),
    migrations.RemoveField(
        model_name='payment',
        name='order',
    ),
    migrations.DeleteModel(
        name='OrderItem',
    ),
    migrations.DeleteModel(
        name='Order',
    ),
    migrations.DeleteModel(
        name='Payment',
    ),
    migrations.AddField(
        model_name='cart',
        name='updated_at',
        field=models.DateTimeField(auto_now=True),
    ),
    migrations.AlterField(
        model_name='cart',
        name='created_at',
        field=models.DateTimeField(default=django.utils.timezone.now),
    ),
    migrations.AlterField(
        model_name='cart',
        name='session_key',
        field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
    ),
    migrations.AddIndex(
        model_name='cart',
        index=models.Index(fields=['user', 'session_key'], name='fitur_belan_user_id_ab7b2f_idx'),
    ),
    migrations.RemoveField(
        model_name='cartitem',
        name='name_snapshot',
    ),
    migrations.RemoveField(
        model_name='cartitem',
        name='price_snapshot',
    ),
    migrations.RemoveField(
        model_name='cartitem',
        name='product_id',
    ),
    migrations.AddField(
        model_name='cartitem',
        name='product',
        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product'),
    ),
    migrations.AddField(
        model_name='cartitem',
        name='unit_price',
        field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
    ),
    migrations.AlterUniqueTogether(
        name='cartitem',
        unique_together={('cart', 'product')},
    ),
]

