# Generated by Django 5.2.7 on 2025-10-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_seed_products_fixed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
